package com.javacore.spring_api_luvine.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    // AUTH
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    PASSWORD_MISMATCH(HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_CODE(HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_VERIFIED(HttpStatus.CONFLICT),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    EMAIL_NOT_VERIFIED(HttpStatus.UNAUTHORIZED),
    PROVIDER_CONFLICT(HttpStatus.UNAUTHORIZED),
    INVALID_AUTHENTICATION_TOKEN(HttpStatus.UNAUTHORIZED),

    // USER
    INVALID_NAME(HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(HttpStatus.BAD_REQUEST),
    INVALID_CEP(HttpStatus.BAD_REQUEST),
    INVALID_PHONE(HttpStatus.BAD_REQUEST),
    USER_SESSION_INVALID(HttpStatus.UNAUTHORIZED),
    ADDRESS_NOT_FOUND(HttpStatus.NOT_FOUND),
    ADDRESS_INACTIVE(HttpStatus.BAD_REQUEST),
    ADDRESS_ALREADY_EXISTS(HttpStatus.CONFLICT),
    UNCHANGED_VALUE(HttpStatus.BAD_REQUEST),
    ROLE_ALREADY_ASSIGNED(HttpStatus.BAD_REQUEST),
    SELF_PROMOTION_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_PERMISSIONS(HttpStatus.FORBIDDEN),
    NO_PROFILE_CHANGES_PROVIDED(HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(HttpStatus.BAD_REQUEST),

    // PRODUCT
    INVALID_CATEGORY_NAME(HttpStatus.BAD_REQUEST),
    INVALID_SLUG(HttpStatus.BAD_REQUEST),
    INVALID_DESCRIPTION(HttpStatus.BAD_REQUEST),
    INVALID_CATEGORY_HIERARCHY(HttpStatus.BAD_REQUEST),
    INVALID_PRODUCT_NAME(HttpStatus.BAD_REQUEST),
    INVALID_MONEY(HttpStatus.BAD_REQUEST),
    INVALID_SKU(HttpStatus.BAD_REQUEST),
    INVALID_COLOR(HttpStatus.BAD_REQUEST),
    INVALID_SIZE(HttpStatus.BAD_REQUEST),
    INVALID_STOCK_QUANTITY(HttpStatus.BAD_REQUEST),
    INSUFFICIENT_STOCK(HttpStatus.BAD_REQUEST),
    IMAGE_ALREADY_PRIMARY(HttpStatus.BAD_REQUEST),
    VARIANT_ALREADY_ACTIVATE(HttpStatus.CONFLICT),
    VARIANT_ALREADY_DEACTIVATE(HttpStatus.CONFLICT),
    CATEGORY_ALREADY_ACTIVE(HttpStatus.CONFLICT),
    CATEGORY_ALREADY_DISABLE(HttpStatus.CONFLICT),
    VARIANT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    DUPLICATED_SKU(HttpStatus.CONFLICT),
    PRODUCT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND),
    CATEGORY_INACTIVE(HttpStatus.BAD_REQUEST),
    EMPTY_PRODUCT_VARIANTS(HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PRODUCT_NOT_AVAILABLE(HttpStatus.CONFLICT),
    VARIANT_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_ALT_TEXT(HttpStatus.BAD_REQUEST),
    INVALID_FILE_UPLOAD(HttpStatus.BAD_REQUEST),
    FILE_STORAGE(HttpStatus.SERVICE_UNAVAILABLE),
    IMAGE_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST),
    IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_IMAGE_REORDER(HttpStatus.BAD_REQUEST),
    CATEGORY_ALREADY_EXISTS(HttpStatus.CONFLICT),
    CIRCULAR_HIERARCHY_DETECTED(HttpStatus.BAD_REQUEST),

    // SHARED
    TOKEN_HASH(HttpStatus.INTERNAL_SERVER_ERROR),
    UNSUPPORTED_OPERATION(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }
}