services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - luvine-network

  valkey:
    image: valkey/valkey:9
    container_name: valkey
    restart: always
    command: valkey-server --appendonly yes --requirepass ${VALKEY_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    networks:
      - luvine-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - luvine-network

volumes:
  postgres-data:
  valkey-data:
  rabbitmq-data:

networks:
  luvine-network:
    driver: bridge